model_name: "tiny_mdm"
arch_name: "DiT"

T: 50
loss_type: 'l1'
estimate_mode: 'epsilon'
noise_schedule_mode: 'squaredcos_cap_v2'

num_layers: 2
num_attention_heads: 4 # inner_dim = heads * 64

model_ema: True
model_ema_decay: 0.995
model_ema_steps: 10
model_ema_update_after: 5_000

normalizer_std_clip: 0.2

device: "cuda"
batch_size: 512
lr: 0.0002
num_iterations: 200_000
num_samples_stat: 20_000
output_iter: 2_000
grad_clip_norm: 1.0

env_config: "data/envs/smp_location_humanoid_env.yaml"
motion_file: "data/datasets/dataset_humanoid_locomotion.yaml"
control_freq: 30

master_port: '11435'
